debug=0                                 # enable/disable debug mode (1/0)
mock=0

[manager]
    max_workers=4                       # number of workers deployed for img analyse
    nth_analysed=2                     # every nth frame from stream will be analysed and the rest "intrapolated"

[logging]
    show_futures_status=0               # display each frame as it is analysed

[input]
    video_input_path='../../grupaA1.mp4'

[output]
    log_file_path='../log.log'          # output path for log file