debug=0                                 # enable/disable debug mode (1/0)
mock=1

[manager]
    max_workers=4                       # number of workers deployed for img analyse

[logging]
    show_futures_status=0               # display each frame as it is analysed

[output]
    log_file_path='../log.log'          # output path for log file